package com.ai.agenticrag.orchestrator;

import com.ai.agenticrag.api.dto.FinalAnswer;
import com.ai.agenticrag.rag.ChunkHit;
import com.ai.agenticrag.rag.Citation;
import org.apache.commons.lang3.builder.ToStringBuilder;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Represents the shared context used by agents in a multi-agent system to facilitate communication
 * and track the state of operations. This context is intended to be mutable and passed across agents,
 * allowing them to collaboratively generate, modify, and evaluate responses based on the input question.
 * <p>
 * Fields:
 * <p>
 * - {@code question}: The original question or input provided by the user. Immutable and does not change across the lifecycle of processing.
 * - {@code query}: The current query generated or modified by agents based on the input question. This may be updated as part of the agent's operation.
 * - {@code needsRetrieval}: A flag indicating whether additional information needs to be retrieved from external sources.
 * - {@code retrieved}: A collection of {@code ChunkHit} objects representing the results retrieved by agents for context or answer synthesis.
 * - {@code draftAnswer}: A draft response generated by agents. This may represent an intermediate or final synthesized answer.
 * - {@code judgedPass}: A boolean flag indicating whether the draft answer has been evaluated as satisfactory by a judging agent.
 * <p>
 * Typical Use Case:
 * The {@code AgentContext} is instantiated at the beginning of a multi-agent orchestration process with the user's input question.
 * It is then passed across multiple agents such as routers, planners, retrievers, synthesizers, and judges. These agents can
 * modify or read the context as they execute their logic. For example:
 * - A query rewrite agent may update {@code query}.
 * - A retrieval agent may populate the {@code retrieved} list with relevant {@code ChunkHit} objects.
 * - A synthesizer agent may generate a {@code draftAnswer}.
 * - A judging agent can use {@code judgedPass} to mark the draft as either acceptable or needing further refinement.
 * <p>
 * Thread-Safety:
 * The `retrieved` and `citations` lists are synchronized for thread-safe access across reactive chains.
 * Other fields are expected to be used in a sequential or controlled manner across agents.
 * It is designed to be mutable, and its properties may be modified as part of the multi-agent orchestration.
 */
public class AgentContext {

    /**
     * Represents the original question or input provided by the user in the context of a multi-agent system.
     * This variable is immutable and serves as the foundational prompt for the orchestration process.
     * <p>
     * Characteristics:
     * - It is initialized upon instantiation of the {@code AgentContext} with the user's input question.
     * - Its value remains constant throughout the lifecycle of the context.
     * <p>
     * Use Case:
     * This field provides the initial context for all agents in the system, aiding in tasks such as
     * generating queries, synthesizing responses, or guiding the flow of operations.
     */
    public final String question;

    /**
     * Represents a query string to be used within the context of an agent's operations.
     * This variable is typically modified or utilized by various agents during their execution
     * to perform tasks such as information retrieval, query rewriting, or contextual synthesis.
     */
    public String query;

    /**
     * Indicates whether retrieval of additional contextual information is needed
     * to process the current query or task.
     * <p>
     * This flag is typically used within the {@code AgentContext} to determine
     * if the multi-agent system should initiate retrieval operations, such as
     * retrieving information from external sources or databases, before proceeding
     * with further processing or generating a final answer.
     * <p>
     * A {@code true} value signifies the necessity for retrieval, while {@code false}
     * indicates that the current context already contains sufficient information
     * for completing the associated task.
     */
    public boolean needsRetrieval;

    /**
     * Represents a list of {@code ChunkHit} objects that have been retrieved
     * during the {@code AgentContext} lifecycle. This list is typically populated
     * when agents execute retrieval operations within their workflows.
     *
     * <ul>
     *   <li>Each {@code ChunkHit} in the list contains details such as the chunk ID,
     *       document ID, title, chunk index, content, and a relevance score.</li>
     *   <li>The list may be cleared and repopulated periodically to store
     *       the most relevant or updated results during the retrieval phase.</li>
     *   <li>This field is primarily used for storing intermediate retrieval results
     *       and can serve as input for further processing steps such as synthesizing
     *       or judging the final result.</li>
     * </ul>
     * <p>
     * The contents of this list are determined by retrieval agents like
     * {@code RetrieverAgent} and are processed based on their respective logic.
     * It should be noted that this is a mutable field and its state may change
     * during the context's lifecycle.
     * <p>
     * THREAD-SAFE: Wrapped with Collections.synchronizedList() for safe concurrent access.
     */
    public final List<ChunkHit> retrieved = Collections.synchronizedList(new ArrayList<>());

    /**
     * Represents the initial draft of an answer generated during the processing of a question.
     * This field serves as a preliminary response produced by an agent or a synthesis step
     * before final validation or refinement occurs.
     * <p>
     * It may be updated or replaced by subsequent processing steps, such as evaluation or
     * context-based retrieval, to ensure the final answer is accurate and grounded.
     * <p>
     * Typically used within the agent execution context to manage state across multiple
     * operations.
     */
    public String draftAnswer;

    /**
     * A flag indicating whether the drafted answer has been evaluated as acceptable or sufficient
     * by the judging agent during the multi-agent system's operation.
     * <p>
     * This field is part of the shared mutable state within the {@code AgentContext} and is used
     * to determine whether further iterations or processing steps (e.g., query rewriting and
     * additional retrievals) are necessary to improve the draft answer.
     * <p>
     * A value of {@code true} signifies that the judging agent has deemed the draft answer
     * satisfactory, allowing the system to proceed to the finalization phase.
     * Conversely, a value of {@code false} indicates the need for further processing or refinement
     * of the drafted answer.
     */
    public boolean judgedPass;

    public List<Citation> citations = Collections.synchronizedList(new ArrayList<>());

    public final String jobId;

    /**
     * Constructs an instance of the AgentContext class using the given question and job identifier.
     *
     * @param question The initial question or query that the agent will process.
     * @param jobId The unique identifier for the job or task associated with this context.
     */
    public AgentContext(String question, String jobId) {
        this.question = question;
        this.jobId = jobId;
        this.query = question;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("question", question)
                .append("query", query)
                .append("needsRetrieval", needsRetrieval)
                .append("retrieved", retrieved)
                .append("draftAnswer", draftAnswer)
                .append("judgedPass", judgedPass)
                .append("citations", citations)
                .append("jobId", jobId)
                .toString();
    }
}
