package com.ai.agenticrag.orchestrator;

import com.ai.agenticrag.api.dto.AgentEvent;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * The Agent interface defines a blueprint for classes that represent individual agents
 * in a multi-agent system. Each agent must have a unique name, a traceable flow of operations,
 * and the ability to execute logic based on shared state.
 */
public interface Agent {

    /**
     * Retrieves the name of the agent.
     * This name is expected to uniquely identify the agent in the multi-agent system.
     *
     * @return A string representing the unique name of the agent.
     */
    String name();

    /**
     * Provides a reactive stream of events generated by the agent based on the given context.
     * These events represent the traceable flow of the agent's operations and can be used
     * for monitoring or debugging purposes within a multi-agent system.
     *
     * @param ctx The shared state used during the agent's execution, containing information such as
     *            the initial question, query modifications, retrieval results, and draft answers.
     * @return A Flux stream emitting AgentEvent objects that describe specific actions or states
     * during the agent's operation.
     */
    Flux<AgentEvent> trace(AgentContext ctx);

    /**
     * Executes the core logic of the agent within the provided context.
     * This method is intended to perform operations using the shared mutable state
     * encapsulated within the {@code AgentContext}, potentially altering the context
     * as part of its execution, and completing without producing a result.
     *
     * @param ctx The shared mutable state used during the agent's execution. This context contains
     *            information such as the initial question, query modifications,
     *            retrieval results, and draft answers.
     * @return A {@code Mono<Void>} that completes when the agent's execution finishes,
     * potentially as a reactive operation.
     */
    Mono<Void> run(AgentContext ctx);

    public static final String GROUNDED_SYSTEM_PROMPT = """
            You are a grounded RAG answer synthesizer.
            
            Rules:
            - Use ONLY the information provided in CONTEXT.
            - Do NOT use outside knowledge.
            - Do NOT say "I don't know" if CONTEXT is non-empty.
            - Extract concrete facts, numbers, tables, or trends.
            - Every paragraph MUST cite at least one chunk using [chunk:{id}].
            - If information is missing, say exactly what is missing and cite closest chunks.

            Answer format:

            Answer:
            <clear factual answer>

            Evidence:
            - [chunk:{id}] <short quote or summary>
            - [chunk:{id}] <short quote or summary>
            """;
}
